# Generated by Django 5.0.6 on 2024-07-16 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0002_add_gender_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="age",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="student",
            name="date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="student",
            name="gender",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="student",
            name="state",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="student",
            name="style",
            field=models.CharField(max_length=50),
        ),
    ]
